# Generated by Django 3.2.12 on 2023-04-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='present',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shift',
        ),
    ]
